### ISSUE TITLE
Include an entity relationship diagram within the docoumentation

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/docs.globaleaks.org#1]
**Summary**
Our documentation lacks useful information about the internal structure of globaleaks. It would be very nice to have up to date entity relationship diagrams shipped with our documentation. Using the python library [eralchemy](https://pypi.python.org/pypi/ERAlchemy) we could include the generation of schema with the MAKE of the documentation.

**Manual Steps**

Follow the following steps to reproduce the graphs by hand:

```bash
> apt install graphviz-dev
> pip install eralchemy
> eralchemy -i sqlite:///globaleaks/tests/db/populated/glbackend-37.db -o entity-relations.pdf
> touch entity-relations.pdf
entity-relations.pdf: PDF document, version 1.5
```

**Example output**
Files generated on 02/08/2017:
- [ER-v2.70.10.pdf](https://github.com/globaleaks/GlobaLeaks/files/1194505/ER-v2.70.10.pdf)
- [ER-v2.67.4-multitenancy-fork.pdf](https://github.com/globaleaks/GlobaLeaks/files/1194509/ER-v2.67.4-multitenancy-fork.pdf)

**Todo**

- Validate build process supports custom logic like this
- Implement install of reqiurements.txt
- Implement move of files into proper assets directory
- (Maybe) add annotation to document version/build dates.

**Comment by evilaliv3** [comment]
Wrong repository.
